### ISSUE TITLE
not showing embed on discord

### ISSUE THREAD

**Issue by JimoYT** [twilsonco/SpeedtestBot#1]
hi this is wat it looks like when i do a speed test 
![image](https://user-images.githubusercontent.com/71781063/120998701-3d1d3e00-c780-11eb-8603-b15c461c5aa1.png) but when i look at the screenshot from here it shows its in a embed but mine aint?

**Comment by twilsonco** [comment]
Holy crap. 2+Gbps! Not to shabby.

It uses an embed if it’s able to properly parse the output of the speedtest program. Something about your (successful) output isn’t what the program expected.

I now see that it has the option for json output, which I’ll update the bot to use instead. Hopefully that makes it more robust across regions/ISPs/etc.

Tim

**Comment by JimoYT** [comment]
ikr lol and perfect tysm also would it be possible to not show the ip? cuz i tried to take it off but if not its good and its very well coded btw

**Comment by twilsonco** [comment]
Yo, updated to use json output, will produce embed all the time now.

**Comment by JimoYT** [comment]
thank you

**Comment by JimoYT** [comment]
um im getting this error now

File "bot.py", line 158, in test
    st = json.loads(subprocess.check_output(SPEEDTEST_TEST).decode())
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by twilsonco** [comment]
updated, try again

**Comment by JimoYT** [comment]
ty but this is the only one now and would u have discord so i can just dm?
File "bot.py", line 162, in test
    await context.message.channel.send(embed=st_to_embed(st,ts))
  File "bot.py", line 111, in st_to_embed
    embed=discord.Embed(title="Speedtest results (view online)", url=st["result"]["url"], color=0x53d6fd)
KeyError: 'result'

**Comment by twilsonco** [comment]
See if you still have this issue. Be sure to update your version of speedtest CLI.
