### ISSUE TITLE
Progress in JSON migration?

### ISSUE THREAD

**Issue by Wintus** [twilsonco/SpeedtestBot#3]
You've mentioned that the program will use the JSON output option of the Speedtest CLI (https://github.com/twilsonco/SpeedtestBot/issues/1#issuecomment-856907879). Is there any progress on it?

# ref.

https://www.speedtest.net/apps/cli

> View test results via CSV, JSONL or JSON

**Comment by twilsonco** [comment]
No I haven’t returned to that. There’s a python json module that makes it easy to convert a json string into a python dict. Shouldn’t be hard.

Tim

**Comment by twilsonco** [comment]
updated with json. working good on my discord server, at least.
