### ISSUE TITLE
could not understand

### ISSUE THREAD

**Issue by JatinJJ1** [twilsonco/SpeedtestBot#4]
Please explain in detail

Set Speedtest CLI information
SPEEDTEST_PATH points to the Speedtest CLI executable
Run with python3 /path/to/SpeedtestBot/bot.py and enjoy!

**Comment by twilsonco** [comment]
See the read me. Links to download page for speedtest CLI program. Once it's installed you need to specify the full program path "eg /use/local/bin/speedtest" or something.

**Comment by twilsonco** [comment]
new version is set to be run in Docker. Can still be run standalone. Let me know if you still have issues.
