### ISSUE TITLE
I don't respond to commands in this channel...

### ISSUE THREAD

**Issue by MapGuy11** [twilsonco/SpeedtestBot#5]
I have done all the required steps and made sure it had Administrative roles and I still get this issue: 
"I don't respond to commands in this channel..."
![image](https://user-images.githubusercontent.com/43685307/170605740-c575bc59-381c-41b4-9944-518df26cacac.png)

**Comment by twilsonco** [comment]
Sounds like you have a missing/incorrect channel id specified at the top of bot.py on line 28

**Comment by MapGuy11** [comment]
Thanks for the response and sorry for my late response I have it like this: (xxx is the channel ID)
CHANNEL_IDS=["xxxxxxxxxxxxxx"]

**Comment by twilsonco** [comment]
Try with no quotes. It should be a comma-delimited list of integers.

**Comment by MapGuy11** [comment]
Thank you it worked!!!
