### ISSUE TITLE
system cannot find the file spcified

### ISSUE THREAD

**Issue by salsa-ig** [twilsonco/SpeedtestBot#6]
![image](https://user-images.githubusercontent.com/45916806/180645015-3dcaec9a-0055-4530-bbd5-c8b0bb5a4b36.png)

**Comment by twilsonco** [comment]
Do these lines in the bot.py file correctly point to the location of the speed test program executable on your machine? 
![image](https://user-images.githubusercontent.com/7284371/180658405-b5b7c1b2-b37f-4a32-b77a-6fcc20b117ac.png)
